insert into tbprofessor (nome_professor)
values
('Adilson Rodolfo Neves'),
('Adriana Antividad López Valverde'),
('André Olímpio'),
('Antonio Egydio S. T. Graça'),
('Arley Ferreira de Souza'),
('Celso de Oliveira'),
('Daniel'),
('Daniel José de Andrade'),
('Érico Luciano Pagotto'),
('Fabrício Galende Marques de Carvalho'),
('Fernanda da Silveira Bueno'),
('Gerson Freitas Júnior'),
('Henique Duarte Borges Louro'),
('Jane Delane Verona'),
('Joanize Aparecida dos Santos Mohallem Paiva'),
('Jorge Tadao Matsushima'),
('Karen Espinosa'),
('Kenji Taniguchi'),
('Lucineide Nunes Pimenta'),
('Luiz Gustavo Galhardo Mendes'),
('Luiz Sérgio Gonçalves Aguiar'),
('Marcelo Augusto Sudo'),
("Maria Lucia de Oliveira"),
('Mariana Timponi Rodrigues'),
('Mario Sérgio Soléo Scalambrino'),
('Matheus de Oliveira Lorena'),
('Nanci de Oliveira'),
('Neymar Siqueira Dellareti '),
('Nilton de Jesus'),
('Paulo José Maria Filho'),
('Renato Mortin'),
('Risleide Lucia dos Santos'),
('Rita de Cássia von Randow'),
('Rodrigo Monteiro de Barros Santana'),
('Ronaldo Emerick Moreira'),
('Sanzara Nhiaia J.C. Hassmann'),
('Selma Candelária Genari'),
('Vivian Hyodo'),
('Wellington Rios'),
('Yara da Cruz Ferreira');