-- INSERTS table: cursos
-- ============================
INSERT INTO cursos (nome) VALUES ('Geoprocessamento');
INSERT INTO cursos (nome) VALUES ('Desenvolvimento de Software Multiplaforma');
INSERT INTO cursos (nome) VALUES ('Meio Ambiente e Recursos Hídricos');


-- INSERTS table: turmas
-- ============================
INSERT INTO turmas (nome , periodo, curso_id) VALUES ('1 semestre', 'noturno', 1);
INSERT INTO turmas (nome , periodo, curso_id) VALUES ('2 semestre', 'noturno', 1);
INSERT INTO turmas (nome , periodo, curso_id) VALUES ('3 semestre', 'noturno', 1);
INSERT INTO turmas (nome , periodo, curso_id) VALUES ('4 semestre', 'noturno', 1);
INSERT INTO turmas (nome , periodo, curso_id) VALUES ('5 semestre', 'noturno', 1);
INSERT INTO turmas (nome , periodo, curso_id) VALUES ('6 semestre', 'noturno', 1);
INSERT INTO turmas (nome , periodo, curso_id) VALUES ('1 semestre', 'noturno', 2);
INSERT INTO turmas (nome , periodo, curso_id) VALUES ('2 semestre', 'noturno', 2);
INSERT INTO turmas (nome , periodo, curso_id) VALUES ('3 semestre', 'noturno', 2);
INSERT INTO turmas (nome , periodo, curso_id) VALUES ('4 semestre', 'noturno', 2);
INSERT INTO turmas (nome , periodo, curso_id) VALUES ('5 semestre', 'noturno', 2);
INSERT INTO turmas (nome , periodo, curso_id) VALUES ('6 semestre', 'noturno', 2);
INSERT INTO turmas (nome , periodo, curso_id) VALUES ('1 semestre', 'noturno', 3);
INSERT INTO turmas (nome , periodo, curso_id) VALUES ('2 semestre', 'noturno', 3);
INSERT INTO turmas (nome , periodo, curso_id) VALUES ('3 semestre', 'noturno', 3);
INSERT INTO turmas (nome , periodo, curso_id) VALUES ('4 semestre', 'noturno', 3);
INSERT INTO turmas (nome , periodo, curso_id) VALUES ('5 semestre', 'diurno', 3);
INSERT INTO turmas (nome , periodo, curso_id) VALUES ('6 semestre', 'diurno', 3);


-- INSERTS table: professores
-- ============================
INSERT INTO professores (nome, email, foto) VALUES ('a definir', 'sem registro', 'default.png'); 
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Dr. Daniel José de Andrade', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Profa. Dra. Vivian Hyodo', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Me. Celso de Oliveira', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Esp. Mariana Timponi Rodrigues', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Profa. Dra. Karen Espinosa', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Profa. Dra. Rita de Cássia von Randow', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Msc. Jane Delane Verona', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Me. Adilson Rodolfo Neves', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Profa. Ma. Yara da Cruz Ferreira', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Me. Kenji Taniguchi', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Profa. Msc. Jane Delane Verona', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Esp. Matheus de Oliveira Lorena', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Dr. Nilton de Jesus', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Profa. Msc. Risleide Lucia dos Santos', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Joanize Aparecida dos Santos Mohallem Paiva', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Me. Antonio Egydio São Thiago Graça', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Esp. Marcelo Augusto Sudo', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Dr. Arley Ferreira de Souza', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Henrique', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Esp. Henrique Duarte Borges Louro', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Esp. André Olímpio', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Profa. Esp. Lucineide Nunes Pimenta', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Dr. Fabrício Galende Marques de Carvalho', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Me. Ronaldo Emerick Moreira', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Profa. Ma. Adriana Antividad López Valverde', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Profa. Dra. Rita de Cássia Silva Von Randow', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Profa. Esp. Maria Lucia de Oliveira', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Esp. Neymar Siqueira Dellareti', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Me. Rodrigo Monteiro de Barros Santana', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Profa. Esp. Joanize Aparecida dos Santos Mohallem Paiva', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Me. Wellington Rios', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Profa. Esp. Mariana Timponi Rodrigues', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Dr. Jorge Tadao Matsushima', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Profa. Dra. Vívian C.C.C. Hyodo', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Dr. Érico Luciano Pagotto', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Dra. Sanzara Nhiaia J.C. Hassmann', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof.Me. Gerson Freitas Júnior', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Ma.Jane Delane Verona', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Profa. Dra. Selma Candelária Genari', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Me. Paulo José Maria Filho', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Profa. Dra. Nanci de Oliveira', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Dr. Renato Mortin', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Me. Gerson Freitas Júnior', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. Dr. Daniel', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. M.Sc. Kenji Taniguchi', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. MSc. Luiz Sérgio Gonçalves Aguiar', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. M. Sc. Mario Sérgio Soléo Scalambrino', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Profa. Dra.Vivian Hyodo', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. M.Sc. Luiz Gustavo Galhardo Mendes', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof.M.Sc. Antonio Egydio S. T. Graça', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof. M.Sc. Paulo José Maria Filho', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Prof.MSc. Luiz Sérgio Gonçalves Aguiar', 'f258acad@cps.sp.gov.br', 'default.png');
INSERT INTO professores (nome, email, foto) VALUES ('Profa. MSc. Fernanda da Silveira Bueno', 'f258acad@cps.sp.gov.br', 'default.png');



-- INSERTS table: materias
-- ============================
INSERT INTO materias (nome, carga) VALUES ('Introdução à Ciência da Geoinformação', '00h');
INSERT INTO materias (nome, carga) VALUES ('Algoritmos e Lógica de Programação', '00h');
INSERT INTO materias (nome, carga) VALUES ('Metodologia', '00h');
INSERT INTO materias (nome, carga) VALUES ('Desenho Técnico', '00h');
INSERT INTO materias (nome, carga) VALUES ('Comunicação', '00h');
INSERT INTO materias (nome, carga) VALUES ('Inglês I', '00h');
INSERT INTO materias (nome, carga) VALUES ('Fundamentos de Física', '00h');
INSERT INTO materias (nome, carga) VALUES ('Cálculo', '00h');
INSERT INTO materias (nome, carga) VALUES ('Estatística', '00h');
INSERT INTO materias (nome, carga) VALUES ('Processamento Digital de Imagens', '00h');
INSERT INTO materias (nome, carga) VALUES ('Inglês III', '00h');
INSERT INTO materias (nome, carga) VALUES ('Geodésia', '00h');
INSERT INTO materias (nome, carga) VALUES ('Topografia e Batimetria', '00h');
INSERT INTO materias (nome, carga) VALUES ('Modelagem de Banco de Dados', '00h');
INSERT INTO materias (nome, carga) VALUES ('Linguagem de Programação II', '00h');
INSERT INTO materias (nome, carga) VALUES ('Análise Ambiental', '00h');
INSERT INTO materias (nome, carga) VALUES ('Fundamentos da administração', '00h');
INSERT INTO materias (nome, carga) VALUES ('Legislação', '00h');
INSERT INTO materias (nome, carga) VALUES ('Web GIS', '00h');
INSERT INTO materias (nome, carga) VALUES ('Infraestrutura e Urbanização', '00h');
INSERT INTO materias (nome, carga) VALUES ('Análise Espacial', '00h');
INSERT INTO materias (nome, carga) VALUES ('Projetos 1', '00h');
INSERT INTO materias (nome, carga) VALUES ('Inglês IV', '00h');
INSERT INTO materias (nome, carga) VALUES ('Posicionamento por Satélite', '00h');
INSERT INTO materias (nome, carga) VALUES ('Fotogrametria Analóg. Digit', '00h');
INSERT INTO materias (nome, carga) VALUES ('Cadastro Técnico Multifinalitário', '00h');
INSERT INTO materias (nome, carga) VALUES ('Geomarketing', '00h');
INSERT INTO materias (nome, carga) VALUES ('Integração e Análise de Dados Territoriais', '00h');
INSERT INTO materias (nome, carga) VALUES ('Inglês VI', '00h');
INSERT INTO materias (nome, carga) VALUES ('Projetos 2', '00h');
INSERT INTO materias (nome, carga) VALUES ('Georreferenciamento de Imóveis Rurais', '00h');
INSERT INTO materias (nome, carga) VALUES ('Padrões de Distribuição de Dados em SIG', '00h');
INSERT INTO materias (nome, carga) VALUES ('Engenharia de Software I', '00h');
INSERT INTO materias (nome, carga) VALUES ('Sistemas Operacionais e Redes de Computadores', '00h');
INSERT INTO materias (nome, carga) VALUES ('Design Digital', '00h');
INSERT INTO materias (nome, carga) VALUES ('Desenvolvimento Web I', '00h');
INSERT INTO materias (nome, carga) VALUES ('Técnicas de Programação I', '00h');
INSERT INTO materias (nome, carga) VALUES ('Engenharia de Software II', '00h');
INSERT INTO materias (nome, carga) VALUES ('Desenvolvimento Web II', '00h');
INSERT INTO materias (nome, carga) VALUES ('Banco de Dados Relacional', '00h');
INSERT INTO materias (nome, carga) VALUES ('Matemática para Computação', '00h');
INSERT INTO materias (nome, carga) VALUES ('Estrutura de Dados', '00h');
INSERT INTO materias (nome, carga) VALUES ('Banco de Dados Não Relacional', '00h');
INSERT INTO materias (nome, carga) VALUES ('Técnicas de Programação II', '00h');
INSERT INTO materias (nome, carga) VALUES ('Gestão Ágil de Projeto de Software', '00h');
INSERT INTO materias (nome, carga) VALUES ('Interação Humano Computador', '00h');
INSERT INTO materias (nome, carga) VALUES ('Álgebra Linear', '00h');
INSERT INTO materias (nome, carga) VALUES ('Desenvolvimento Web III', '00h');
INSERT INTO materias (nome, carga) VALUES ('Programação para Dispositivos Móveis I', '00h');
INSERT INTO materias (nome, carga) VALUES ('Integração e Entrega Contínua', '00h');
INSERT INTO materias (nome, carga) VALUES ('Laboratório de Desenvolvimento Web', '00h');
INSERT INTO materias (nome, carga) VALUES ('Internet das Coisas e Aplicações', '00h');
INSERT INTO materias (nome, carga) VALUES ('Estatística Aplicada', '00h');
INSERT INTO materias (nome, carga) VALUES ('Experiência do Usuário', '00h');
INSERT INTO materias (nome, carga) VALUES ('Inglês II', '00h');
INSERT INTO materias (nome, carga) VALUES ('Segurança no Desenvolvimento de Aplicações', '00h');
INSERT INTO materias (nome, carga) VALUES ('Programação para Dispositivos Móveis II', '00h');
INSERT INTO materias (nome, carga) VALUES ('Aprendizagem de Máquina', '00h');
INSERT INTO materias (nome, carga) VALUES ('Laboratório de Desenvolvimento para Dispositivos Móveis', '00h');
INSERT INTO materias (nome, carga) VALUES ('Computação em Nuvem I', '00h');
INSERT INTO materias (nome, carga) VALUES ('Fundamentos da Redação técnica', '00h');
INSERT INTO materias (nome, carga) VALUES ('Ciencias Ambientais e das Águas', '00h');
INSERT INTO materias (nome, carga) VALUES ('Fundamentos da Comunicação Empresarial', '00h');
INSERT INTO materias (nome, carga) VALUES ('Química Geral', '00h');
INSERT INTO materias (nome, carga) VALUES ('Sociologia Ambiental', '00h');
INSERT INTO materias (nome, carga) VALUES ('Biologia', '00h');
INSERT INTO materias (nome, carga) VALUES ('Matemática Aplicada', '00h');
INSERT INTO materias (nome, carga) VALUES ('Geociência Ambiental', '00h');
INSERT INTO materias (nome, carga) VALUES ('SERE', '00h');
INSERT INTO materias (nome, carga) VALUES ('Hidrologia e Recursos Hídricos', '00h');
INSERT INTO materias (nome, carga) VALUES ('Cartografia, Topografia e Batimetria', '00h');
INSERT INTO materias (nome, carga) VALUES ('Físico Química Ambiental', '00h');
INSERT INTO materias (nome, carga) VALUES ('Microbiologia', '00h');
INSERT INTO materias (nome, carga) VALUES ('Ecologia', '00h');
INSERT INTO materias (nome, carga) VALUES ('Climatologia e Meteorologia', '00h');
INSERT INTO materias (nome, carga) VALUES ('Hidráulica Fluvial', '00h');
INSERT INTO materias (nome, carga) VALUES ('Gestão da Qualidade', '00h');
INSERT INTO materias (nome, carga) VALUES ('Limnologia', '00h');
INSERT INTO materias (nome, carga) VALUES ('Saneamento Ambiental I', '00h');
INSERT INTO materias (nome, carga) VALUES ('Planejamento e Conservação Ambiental', '00h');
INSERT INTO materias (nome, carga) VALUES ('IPDI', '00h');
INSERT INTO materias (nome, carga) VALUES ('Legislação Ambiental', '00h');
INSERT INTO materias (nome, carga) VALUES ('Águas Subterrâneas', '00h');
INSERT INTO materias (nome, carga) VALUES ('Planej e Gestão Urbana', '00h');
INSERT INTO materias (nome, carga) VALUES ('Projetos Ambientais I', '00h');
INSERT INTO materias (nome, carga) VALUES ('Controle e Monitoramento de Poluição Atmosférica', '00h');
INSERT INTO materias (nome, carga) VALUES ('Ecotecnologia', '00h');
INSERT INTO materias (nome, carga) VALUES ('Gerenciamento de Resíduos', '00h');
INSERT INTO materias (nome, carga) VALUES ('Sistema de Gestão e Auditoria Ambiental', '00h');
INSERT INTO materias (nome, carga) VALUES ('Projetos Ambientais II', '00h');
INSERT INTO materias (nome, carga) VALUES ('Revitalização de Rios e Recuperação de Nascentes', '00h');
INSERT INTO materias (nome, carga) VALUES ('Planejamento de Bacias Hidrográficas', '00h');
INSERT INTO materias (nome, carga) VALUES ('Turismo Meio Ambiente e Recursos Hídricos', '00h');
INSERT INTO materias (nome, carga) VALUES ('Energias Alternativas', '00h');


-- INSERTS table: salas
-- ============================
INSERT INTO salas (nome , andar) VALUES ('a definir', 'a definir');
INSERT INTO salas (nome , andar) VALUES ('Depósito', 'Térreo');
INSERT INTO salas (nome , andar) VALUES ('Copa e Sala de Reuniões', 'Térreo');
INSERT INTO salas (nome , andar) VALUES ('Secretaria Administrativa', 'Térreo');
INSERT INTO salas (nome , andar) VALUES ('Sala dos Professores', 'Térreo');
INSERT INTO salas (nome , andar) VALUES ('Coordenações de Cursos', 'Térreo');
INSERT INTO salas (nome , andar) VALUES ('Direção', 'Térreo');
INSERT INTO salas (nome , andar) VALUES ('Secretaria Acadêmica', 'Térreo');
INSERT INTO salas (nome , andar) VALUES ('Sanitários dos Servidores', 'Térreo');
INSERT INTO salas (nome , andar) VALUES ('Servidor', 'Térreo');
INSERT INTO salas (nome , andar) VALUES ('Sanitários ', 'Térreo');
INSERT INTO salas (nome , andar) VALUES ('Laboratório de Análises Ambientais', 'Térreo');
INSERT INTO salas (nome , andar) VALUES ('Laboratório de Desenho e Topografia', 'Térreo');
INSERT INTO salas (nome , andar) VALUES ('Laboratório de Microbiologia Ambiental', 'Térreo');
INSERT INTO salas (nome , andar) VALUES ('Laboratório de Química Ambiental', 'Térreo');
INSERT INTO salas (nome , andar) VALUES ('Laboratório de Informática 101', 'Primeiro Andar');
INSERT INTO salas (nome , andar) VALUES ('Laboratório de Informática 103', 'Primeiro Andar');
INSERT INTO salas (nome , andar) VALUES ('Laboratório de Informática 105', 'Primeiro Andar');
INSERT INTO salas (nome , andar) VALUES ('Laboratório de Informática 107', 'Primeiro Andar');
INSERT INTO salas (nome , andar) VALUES ('Laboratório de Informática 108', 'Primeiro Andar');
INSERT INTO salas (nome , andar) VALUES ('Biblioteca 109', 'Primeiro Andar');
INSERT INTO salas (nome , andar) VALUES ('Sala de Aula 102', 'Primeiro Andar');
INSERT INTO salas (nome , andar) VALUES ('Sala de Aula 104', 'Primeiro Andar');
INSERT INTO salas (nome , andar) VALUES ('Sala de Aula 106', 'Primeiro Andar');
INSERT INTO salas (nome , andar) VALUES ('Sala Maker 110', 'Primeiro Andar');
INSERT INTO salas (nome , andar) VALUES ('Sanitários', 'Primeiro Andar');
INSERT INTO salas (nome , andar) VALUES ('Coordenação Univesp', 'Primeiro Andar');
INSERT INTO salas (nome , andar) VALUES ('Sala de Aula  202', 'Segundo Andar');
INSERT INTO salas (nome , andar) VALUES ('Sala de Aula 204', 'Segundo Andar');
INSERT INTO salas (nome , andar) VALUES ('Sala de Aula 206', 'Segundo Andar');
INSERT INTO salas (nome , andar) VALUES ('Sala de Áudio e Vídeo 201', 'Segundo Andar');
INSERT INTO salas (nome , andar) VALUES ('Laboratório Univesp 203', 'Segundo Andar');
INSERT INTO salas (nome , andar) VALUES ('Laboratório Informática 205', 'Segundo Andar');
INSERT INTO salas (nome , andar) VALUES ('Laboratório Informática 207', 'Segundo Andar');
INSERT INTO salas (nome , andar) VALUES ('Laboratório Informática 209', 'Segundo Andar');
INSERT INTO salas (nome , andar) VALUES ('Sala de Áudio e Vídeo 210', 'Segundo Andar');
INSERT INTO salas (nome , andar) VALUES ('Laboratório de Biologia', 'Segundo Andar');
INSERT INTO salas (nome , andar) VALUES ('Coordenação de Estágios', 'Segundo Andar');


-- INSERTS table: horarios
-- ============================
INSERT INTO horarios (hora_inicio, hora_fim) VALUES ('18:45', '19:35');
INSERT INTO horarios (hora_inicio, hora_fim) VALUES ('19:35', '20:25');
INSERT INTO horarios (hora_inicio, hora_fim) VALUES ('20:25', '21:15');
INSERT INTO horarios (hora_inicio, hora_fim) VALUES ('21:25', '22:15');
INSERT INTO horarios (hora_inicio, hora_fim) VALUES ('22:15', '23:05');
INSERT INTO horarios (hora_inicio, hora_fim) VALUES ('07:30', '08:20');
INSERT INTO horarios (hora_inicio, hora_fim) VALUES ('08:20', '09:10');
INSERT INTO horarios (hora_inicio, hora_fim) VALUES ('09:20', '10:10');
INSERT INTO horarios (hora_inicio, hora_fim) VALUES ('10:10', '11:00');
INSERT INTO horarios (hora_inicio, hora_fim) VALUES ('11:10', '12:20');
INSERT INTO horarios (hora_inicio, hora_fim) VALUES ('12:00', '12:50');


-- INSERTS table: aulas
-- ============================
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (1, 1, 1, 2, 1, 1, 1, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (2, 1, 1, 1, 2, 1, 2, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (3, 1, 1, 1, 2, 1, 3, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (4, 1, 1, 3, 3, 1, 4, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (5, 1, 1, 3, 3, 1, 5, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (6, 1, 1, 4, 4, 1, 1, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (7, 1, 1, 4, 4, 1, 2, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (8, 1, 1, 4, 4, 1, 3, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (9, 1, 1, 4, 4, 1, 4, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (10, 1, 1, 5, 5, 1, 5, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (11, 1, 1, 1, 2, 1, 1, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (12, 1, 1, 1, 2, 1, 2, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (13, 1, 1, 5, 6, 1, 3, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (14, 1, 1, 5, 6, 1, 4, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (15, 1, 1, 5, 5, 1, 5, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (16, 1, 1, 2, 1, 1, 1, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (17, 1, 1, 2, 1, 1, 2, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (18, 1, 1, 2, 1, 1, 3, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (19, 1, 1, 6, 7, 1, 4, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (20, 1, 1, 6, 7, 1, 5, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (21, 1, 1, 1, 8, 1, 1, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (22, 1, 1, 1, 8, 1, 2, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (23, 1, 1, 1, 8, 1, 3, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (24, 1, 1, 1, 8, 1, 4, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (25, 1, 1, NULL, NULL, 1, 5, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (26, 1, 2, NULL, NULL, 1, 1, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (27, 1, 2, NULL, NULL, 1, 2, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (28, 1, 2, NULL, NULL, 1, 3, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (29, 1, 2, NULL, NULL, 1, 4, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (30, 1, 2, NULL, NULL, 1, 5, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (31, 1, 2, NULL, NULL, 1, 1, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (32, 1, 2, NULL, NULL, 1, 2, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (33, 1, 2, NULL, NULL, 1, 3, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (34, 1, 2, NULL, NULL, 1, 4, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (35, 1, 2, NULL, NULL, 1, 5, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (36, 1, 2, NULL, NULL, 1, 1, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (37, 1, 2, NULL, NULL, 1, 2, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (38, 1, 2, NULL, NULL, 1, 3, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (39, 1, 2, NULL, NULL, 1, 4, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (40, 1, 2, NULL, NULL, 1, 5, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (41, 1, 2, NULL, NULL, 1, 1, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (42, 1, 2, NULL, NULL, 1, 2, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (43, 1, 2, NULL, NULL, 1, 3, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (44, 1, 2, NULL, NULL, 1, 4, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (45, 1, 2, NULL, NULL, 1, 5, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (46, 1, 2, NULL, NULL, 1, 1, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (47, 1, 2, NULL, NULL, 1, 2, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (48, 1, 2, NULL, NULL, 1, 3, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (49, 1, 2, NULL, NULL, 1, 4, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (50, 1, 2, NULL, NULL, 1, 5, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (51, 1, 3, 7, 9, 1, 1, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (52, 1, 3, 7, 9, 1, 2, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (53, 1, 3, 7, 9, 1, 3, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (54, 1, 3, 7, 9, 1, 4, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (55, 1, 3, 8, 10, 1, 5, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (56, 1, 3, 5, 11, 1, 1, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (57, 1, 3, 5, 11, 1, 2, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (58, 1, 3, 9, 12, 1, 3, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (59, 1, 3, 9, 13, 1, 4, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (60, 1, 3, 9, 13, 1, 5, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (61, 1, 3, 9, 13, 1, 1, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (62, 1, 3, 9, 13, 1, 2, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (63, 1, 3, 8, 10, 1, 3, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (64, 1, 3, 8, 10, 1, 4, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (65, 1, 3, 8, 10, 1, 5, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (66, 1, 3, 10, 14, 1, 1, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (67, 1, 3, 10, 14, 1, 2, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (68, 1, 3, 10, 14, 1, 3, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (69, 1, 3, 10, 14, 1, 4, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (70, 1, 3, 9, 12, 1, 5, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (71, 1, 3, 11, 15, 1, 1, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (72, 1, 3, 11, 15, 1, 2, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (73, 1, 3, 11, 15, 1, 3, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (74, 1, 3, 11, 15, 1, 4, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (75, 1, 3, NULL, NULL, 1, 5, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (76, 1, 4, NULL, NULL, 1, 1, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (77, 1, 4, NULL, NULL, 1, 2, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (78, 1, 4, NULL, NULL, 1, 3, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (79, 1, 4, NULL, NULL, 1, 4, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (80, 1, 4, NULL, NULL, 1, 5, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (81, 1, 4, NULL, NULL, 1, 1, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (82, 1, 4, NULL, NULL, 1, 2, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (83, 1, 4, NULL, NULL, 1, 3, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (84, 1, 4, NULL, NULL, 1, 4, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (85, 1, 4, NULL, NULL, 1, 5, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (86, 1, 4, NULL, NULL, 1, 1, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (87, 1, 4, NULL, NULL, 1, 2, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (88, 1, 4, NULL, NULL, 1, 3, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (89, 1, 4, NULL, NULL, 1, 4, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (90, 1, 4, NULL, NULL, 1, 5, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (91, 1, 4, NULL, NULL, 1, 1, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (92, 1, 4, NULL, NULL, 1, 2, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (93, 1, 4, NULL, NULL, 1, 3, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (94, 1, 4, NULL, NULL, 1, 4, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (95, 1, 4, NULL, NULL, 1, 5, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (96, 1, 4, NULL, NULL, 1, 1, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (97, 1, 4, NULL, NULL, 1, 2, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (98, 1, 4, NULL, NULL, 1, 3, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (99, 1, 4, NULL, NULL, 1, 4, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (100, 1, 4, NULL, NULL, 1, 5, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (101, 1, 5, 12, 16, 1, 1, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (102, 1, 5, 12, 16, 1, 2, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (103, 1, 5, 13, 17, 1, 3, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (104, 1, 5, 13, 18, 1, 4, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (105, 1, 5, 13, 18, 1, 5, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (106, 1, 5, 11, 19, 1, 1, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (107, 1, 5, 11, 19, 1, 2, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (108, 1, 5, 11, 19, 1, 3, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (109, 1, 5, 11, 19, 1, 4, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (110, 1, 5, NULL, NULL, 1, 5, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (111, 1, 5, 12, 16, 1, 1, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (112, 1, 5, 12, 16, 1, 2, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (113, 1, 5, 2, 20, 1, 3, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (114, 1, 5, 2, 20, 1, 4, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (115, 1, 5, 2, 20, 1, 5, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (116, 1, 5, 13, 21, 1, 1, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (117, 1, 5, 13, 21, 1, 2, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (118, 1, 5, 13, 21, 1, 3, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (119, 1, 5, 13, 21, 1, 4, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (120, 1, 5, 13, 17, 1, 5, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (121, 1, 5, 14, 22, 1, 1, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (122, 1, 5, 14, 22, 1, 2, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (123, 1, 5, 2, 20, 1, 3, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (124, 1, 5, 15, 23, 1, 4, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (125, 1, 5, 15, 23, 1, 5, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (126, 1, 6, 13, 24, 1, 1, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (127, 1, 6, 13, 24, 1, 2, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (128, 1, 6, 9, 25, 1, 3, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (129, 1, 6, 9, 25, 1, 4, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (130, 1, 6, 9, 25, 1, 5, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (131, 1, 6, 10, 26, 1, 1, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (132, 1, 6, 10, 26, 1, 2, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (133, 1, 6, 10, 27, 1, 3, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (134, 1, 6, 10, 27, 1, 4, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (135, 1, 6, 10, 27, 1, 5, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (136, 1, 6, 14, 28, 1, 1, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (137, 1, 6, 14, 28, 1, 2, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (138, 1, 6, 9, 25, 1, 3, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (139, 1, 6, 16, 29, 1, 4, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (140, 1, 6, 16, 29, 1, 5, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (141, 1, 6, 6, 30, 1, 1, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (142, 1, 6, 6, 30, 1, 2, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (143, 1, 6, 9, 31, 1, 3, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (144, 1, 6, 9, 31, 1, 4, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (145, 1, 6, 10, 27, 1, 5, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (146, 1, 6, 2, 32, 1, 1, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (147, 1, 6, 2, 32, 1, 2, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (148, 1, 6, 14, 28, 1, 3, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (149, 1, 6, 14, 28, 1, 4, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (150, 1, 6, NULL, NULL, 1, 5, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (151, 2, 7, 17, 33, 1, 1, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (152, 2, 7, 17, 33, 1, 2, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (153, 2, 7, 17, 33, 1, 3, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (154, 2, 7, 17, 33, 1, 4, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (155, 2, 7, 17, 34, 1, 5, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (156, 2, 7, 18, 14, 1, 1, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (157, 2, 7, 18, 14, 1, 2, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (158, 2, 7, 18, 14, 1, 3, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (159, 2, 7, 18, 35, 1, 4, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (160, 2, 7, 18, 35, 1, 5, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (161, 2, 7, 19, 2, 1, 1, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (162, 2, 7, 19, 2, 1, 2, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (163, 2, 7, 19, 2, 1, 3, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (164, 2, 7, 19, 2, 1, 4, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (165, 2, 7, NULL, NULL, 1, 5, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (166, 2, 7, 17, 34, 1, 1, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (167, 2, 7, 17, 34, 1, 2, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (168, 2, 7, 17, 34, 1, 3, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (169, 2, 7, 18, 35, 1, 4, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (170, 2, 7, 18, 35, 1, 5, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (171, 2, 7, 20, 36, 1, 1, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (172, 2, 7, 20, 36, 1, 2, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (173, 2, 7, 20, 36, 1, 3, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (174, 2, 7, 20, 36, 1, 4, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (175, 2, 7, 18, 14, 1, 5, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (176, 2, 8, 21, 37, 1, 1, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (177, 2, 8, 21, 37, 1, 2, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (178, 2, 8, 21, 37, 1, 3, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (179, 2, 8, 21, 37, 1, 4, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (180, 2, 8, 22, 38, 1, 5, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (181, 2, 8, 19, 39, 1, 1, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (182, 2, 8, 19, 39, 1, 2, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (183, 2, 8, 19, 39, 1, 3, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (184, 2, 8, 23, 40, 1, 4, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (185, 2, 8, 23, 40, 1, 5, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (186, 2, 8, 24, 41, 1, 1, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (187, 2, 8, 24, 41, 1, 2, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (188, 2, 8, 24, 41, 1, 3, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (189, 2, 8, 24, 41, 1, 4, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (190, 2, 8, 19, 39, 1, 5, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (191, 2, 8, 24, 42, 1, 1, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (192, 2, 8, 24, 42, 1, 2, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (193, 2, 8, 24, 42, 1, 3, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (194, 2, 8, 24, 42, 1, 4, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (195, 2, 8, NULL, NULL, 1, 5, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (196, 2, 8, 22, 38, 1, 1, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (197, 2, 8, 22, 38, 1, 2, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (198, 2, 8, 22, 38, 1, 3, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (199, 2, 8, 23, 40, 1, 4, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (200, 2, 8, 23, 40, 1, 5, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (201, 2, 9, 23, 43, 1, 1, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (202, 2, 9, 23, 43, 1, 2, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (203, 2, 9, 23, 43, 1, 3, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (204, 2, 9, 23, 43, 1, 4, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (205, 2, 9, 21, 44, 1, 5, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (206, 2, 9, 25, 45, 1, 1, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (207, 2, 9, 25, 45, 1, 2, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (208, 2, 9, 25, 45, 1, 3, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (209, 2, 9, 26, 46, 1, 4, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (210, 2, 9, 26, 46, 1, 5, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (211, 2, 9, 27, 47, 1, 1, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (212, 2, 9, 27, 47, 1, 2, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (213, 2, 9, 27, 47, 1, 3, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (214, 2, 9, 27, 47, 1, 4, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (215, 2, 9, 25, 45, 1, 5, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (216, 2, 9, 21, 44, 1, 1, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (217, 2, 9, 21, 44, 1, 2, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (218, 2, 9, 21, 44, 1, 3, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (219, 2, 9, 28, 6, 1, 4, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (220, 2, 9, 28, 6, 1, 5, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (221, 2, 9, 29, 48, 1, 1, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (222, 2, 9, 29, 48, 1, 2, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (223, 2, 9, 29, 48, 1, 3, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (224, 2, 9, 29, 48, 1, 4, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (225, 2, 9, NULL, NULL, 1, 5, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (226, 2, 10, 22, 49, 1, 1, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (227, 2, 10, 22, 49, 1, 2, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (228, 2, 10, 22, 49, 1, 3, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (229, 2, 10, 22, 49, 1, 4, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (230, 2, 10, 23, 50, 1, 5, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (231, 2, 10, 29, 51, 1, 1, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (232, 2, 10, 29, 51, 1, 2, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (233, 2, 10, 29, 51, 1, 3, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (234, 2, 10, 29, 51, 1, 4, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (235, 2, 10, NULL, NULL, 1, 5, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (236, 2, 10, 30, 52, 1, 1, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (237, 2, 10, 30, 52, 1, 2, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (238, 2, 10, 30, 52, 1, 3, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (239, 2, 10, 30, 52, 1, 4, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (240, 2, 10, 27, 53, 1, 5, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (241, 2, 10, 27, 53, 1, 1, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (242, 2, 10, 27, 53, 1, 2, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (243, 2, 10, 27, 53, 1, 3, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (244, 2, 10, 23, 54, 1, 4, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (245, 2, 10, 23, 54, 1, 5, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (246, 2, 10, 23, 50, 1, 1, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (247, 2, 10, 23, 50, 1, 2, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (248, 2, 10, 23, 50, 1, 3, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (249, 2, 10, 28, 55, 1, 4, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (250, 2, 10, 28, 55, 1, 5, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (251, 2, 11, 1, 56, 1, 1, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (252, 2, 11, 1, 56, 1, 2, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (253, 2, 11, 1, 56, 1, 3, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (254, 2, 11, 1, 56, 1, 4, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (255, 2, 11, 1, 57, 1, 5, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (256, 2, 11, 1, 58, 1, 1, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (257, 2, 11, 1, 58, 1, 2, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (258, 2, 11, 1, 58, 1, 3, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (259, 2, 11, 1, 59, 1, 4, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (260, 2, 11, 1, 59, 1, 5, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (261, 2, 11, 25, 60, 1, 1, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (262, 2, 11, 25, 60, 1, 2, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (263, 2, 11, 25, 60, 1, 3, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (264, 2, 11, 25, 60, 1, 4, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (265, 2, 11, 1, 58, 1, 5, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (266, 2, 11, 1, 59, 1, 1, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (267, 2, 11, 1, 59, 1, 2, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (268, 2, 11, 1, 57, 1, 3, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (269, 2, 11, 1, 57, 1, 4, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (270, 2, 11, 1, 57, 1, 5, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (271, 2, 11, 31, 11, 1, 1, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (272, 2, 11, 31, 11, 1, 2, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (273, 2, 11, 1, 61, 1, 3, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (274, 2, 11, 1, 61, 1, 4, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (275, 2, 11, NULL, NULL, 1, 5, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (276, 2, 12, NULL, NULL, 1, 1, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (277, 2, 12, NULL, NULL, 1, 2, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (278, 2, 12, NULL, NULL, 1, 3, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (279, 2, 12, NULL, NULL, 1, 4, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (280, 2, 12, NULL, NULL, 1, 5, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (281, 2, 12, NULL, NULL, 1, 1, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (282, 2, 12, NULL, NULL, 1, 2, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (283, 2, 12, NULL, NULL, 1, 3, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (284, 2, 12, NULL, NULL, 1, 4, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (285, 2, 12, NULL, NULL, 1, 5, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (286, 2, 12, NULL, NULL, 1, 1, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (287, 2, 12, NULL, NULL, 1, 2, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (288, 2, 12, NULL, NULL, 1, 3, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (289, 2, 12, NULL, NULL, 1, 4, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (290, 2, 12, NULL, NULL, 1, 5, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (291, 2, 12, NULL, NULL, 1, 1, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (292, 2, 12, NULL, NULL, 1, 2, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (293, 2, 12, NULL, NULL, 1, 3, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (294, 2, 12, NULL, NULL, 1, 4, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (295, 2, 12, NULL, NULL, 1, 5, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (296, 2, 12, NULL, NULL, 1, 1, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (297, 2, 12, NULL, NULL, 1, 2, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (298, 2, 12, NULL, NULL, 1, 3, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (299, 2, 12, NULL, NULL, 1, 4, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (300, 2, 12, NULL, NULL, 1, 5, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (301, 3, 13, 32, 62, 1, 1, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (302, 3, 13, 32, 62, 1, 2, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (303, 3, 13, 33, 6, 1, 3, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (304, 3, 13, 33, 6, 1, 4, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (305, 3, 13, 33, 63, 1, 5, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (306, 3, 13, 34, 64, 1, 1, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (307, 3, 13, 34, 64, 1, 2, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (308, 3, 13, 33, 63, 1, 3, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (309, 3, 13, 35, 3, 1, 4, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (310, 3, 13, 35, 3, 1, 5, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (311, 3, 13, 34, 64, 1, 1, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (312, 3, 13, 34, 64, 1, 2, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (313, 3, 13, 36, 65, 1, 3, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (314, 3, 13, 36, 65, 1, 4, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (315, 3, 13, NULL, NULL, 1, 5, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (316, 3, 13, 35, 66, 1, 1, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (317, 3, 13, 37, 67, 1, 2, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (318, 3, 13, 37, 67, 1, 3, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (319, 3, 13, 37, 67, 1, 4, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (320, 3, 13, 37, 67, 1, 5, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (321, 3, 13, 35, 66, 1, 1, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (322, 3, 13, 35, 66, 1, 2, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (323, 3, 13, 35, 66, 1, 3, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (324, 3, 13, 38, 68, 1, 4, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (325, 3, 13, 38, 68, 1, 5, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (326, 3, 14, 33, 55, 1, 1, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (327, 3, 14, 33, 55, 1, 2, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (328, 3, 14, 39, 69, 1, 3, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (329, 3, 14, 39, 69, 1, 4, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (330, 3, 14, 7, 70, 1, 5, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (331, 3, 14, 9, 71, 1, 1, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (332, 3, 14, 9, 71, 1, 2, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (333, 3, 14, 34, 72, 1, 3, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (334, 3, 14, 34, 72, 1, 4, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (335, 3, 14, 34, 72, 1, 5, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (336, 3, 14, 40, 73, 1, 1, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (337, 3, 14, 40, 73, 1, 2, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (338, 3, 14, 34, 72, 1, 3, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (339, 3, 14, 9, 71, 1, 4, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (340, 3, 14, 9, 71, 1, 5, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (341, 3, 14, NULL, NULL, 1, 1, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (342, 3, 14, 35, 74, 1, 2, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (343, 3, 14, 35, 74, 1, 3, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (344, 3, 14, 7, 75, 1, 4, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (345, 3, 14, 7, 75, 1, 5, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (346, 3, 14, 7, 70, 1, 1, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (347, 3, 14, 7, 70, 1, 2, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (348, 3, 14, 7, 70, 1, 3, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (349, 3, 14, 35, 74, 1, 4, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (350, 3, 14, 35, 74, 1, 5, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (351, 3, 15, 41, 76, 1, 1, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (352, 3, 15, 42, 9, 1, 2, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (353, 3, 15, 42, 9, 1, 3, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (354, 3, 15, 42, 9, 1, 4, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (355, 3, 15, 42, 9, 1, 5, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (356, 3, 15, 43, 77, 1, 1, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (357, 3, 15, 43, 77, 1, 2, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (358, 3, 15, 35, 78, 1, 3, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (359, 3, 15, 1, 11, 1, 4, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (360, 3, 15, 1, 11, 1, 5, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (361, 3, 15, 35, 79, 1, 1, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (362, 3, 15, 35, 79, 1, 2, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (363, 3, 15, 35, 78, 1, 3, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (364, 3, 15, 35, 78, 1, 4, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (365, 3, 15, 35, 78, 1, 5, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (366, 3, 15, 41, 76, 1, 1, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (367, 3, 15, 41, 76, 1, 2, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (368, 3, 15, 41, 76, 1, 3, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (369, 3, 15, 35, 79, 1, 4, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (370, 3, 15, 35, 79, 1, 5, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (371, 3, 15, NULL, NULL, 1, 1, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (372, 3, 15, 44, 80, 1, 2, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (373, 3, 15, 44, 80, 1, 3, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (374, 3, 15, 45, 81, 1, 4, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (375, 3, 15, 45, 81, 1, 5, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (376, 3, 16, NULL, NULL, 1, 1, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (377, 3, 16, NULL, NULL, 1, 2, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (378, 3, 16, NULL, NULL, 1, 3, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (379, 3, 16, NULL, NULL, 1, 4, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (380, 3, 16, NULL, NULL, 1, 5, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (381, 3, 16, NULL, NULL, 1, 1, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (382, 3, 16, NULL, NULL, 1, 2, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (383, 3, 16, NULL, NULL, 1, 3, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (384, 3, 16, NULL, NULL, 1, 4, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (385, 3, 16, NULL, NULL, 1, 5, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (386, 3, 16, NULL, NULL, 1, 1, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (387, 3, 16, NULL, NULL, 1, 2, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (388, 3, 16, NULL, NULL, 1, 3, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (389, 3, 16, NULL, NULL, 1, 4, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (390, 3, 16, NULL, NULL, 1, 5, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (391, 3, 16, NULL, NULL, 1, 1, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (392, 3, 16, NULL, NULL, 1, 2, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (393, 3, 16, NULL, NULL, 1, 3, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (394, 3, 16, NULL, NULL, 1, 4, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (395, 3, 16, NULL, NULL, 1, 5, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (396, 3, 16, NULL, NULL, 1, 1, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (397, 3, 16, NULL, NULL, 1, 2, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (398, 3, 16, NULL, NULL, 1, 3, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (399, 3, 16, NULL, NULL, 1, 4, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (400, 3, 16, NULL, NULL, 1, 5, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (401, 3, 17, 46, 82, 1, 6, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (402, 3, 17, 46, 82, 1, 7, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (403, 3, 17, 46, 82, 1, 8, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (404, 3, 17, 46, 82, 1, 9, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (405, 3, 17, 47, 83, 1, 10, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (406, 3, 17, 47, 83, 1, 11, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (407, 3, 17, NULL, NULL, 1, 6, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (408, 3, 17, NULL, NULL, 1, 7, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (409, 3, 17, NULL, NULL, 1, 8, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (410, 3, 17, NULL, NULL, 1, 9, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (411, 3, 17, NULL, NULL, 1, 10, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (412, 3, 17, NULL, NULL, 1, 11, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (413, 3, 17, 48, 84, 1, 6, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (414, 3, 17, 48, 84, 1, 7, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (415, 3, 17, 48, 84, 1, 8, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (416, 3, 17, 48, 84, 1, 9, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (417, 3, 17, 47, 83, 1, 10, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (418, 3, 17, 47, 83, 1, 11, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (419, 3, 17, 49, 85, 1, 6, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (420, 3, 17, 49, 85, 1, 7, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (421, 3, 17, 50, 86, 1, 8, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (422, 3, 17, 50, 86, 1, 9, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (423, 3, 17, 50, 87, 1, 10, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (424, 3, 17, 50, 87, 1, 11, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (425, 3, 17, 50, 88, 1, 6, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (426, 3, 17, 50, 88, 1, 7, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (427, 3, 17, 50, 87, 1, 8, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (428, 3, 17, 50, 87, 1, 9, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (429, 3, 17, 51, 89, 1, 10, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (430, 3, 17, 51, 89, 1, 11, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (431, 3, 18, NULL, NULL, 1, 6, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (432, 3, 18, NULL, NULL, 1, 7, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (433, 3, 18, 52, 90, 1, 8, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (434, 3, 18, 52, 90, 1, 9, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (435, 3, 18, 52, 90, 1, 10, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (436, 3, 18, 52, 90, 1, 11, 'Segunda');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (437, 3, 18, 53, 91, 1, 6, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (438, 3, 18, 53, 91, 1, 7, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (439, 3, 18, 53, 91, 1, 8, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (440, 3, 18, 53, 91, 1, 9, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (441, 3, 18, 53, 92, 1, 10, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (442, 3, 18, 53, 92, 1, 11, 'Terça');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (443, 3, 18, NULL, NULL, 1, 6, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (444, 3, 18, NULL, NULL, 1, 7, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (445, 3, 18, 54, 93, 1, 8, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (446, 3, 18, 54, 93, 1, 9, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (447, 3, 18, 54, 93, 1, 10, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (448, 3, 18, 54, 93, 1, 11, 'Quarta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (449, 3, 18, 43, 94, 1, 6, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (450, 3, 18, 43, 94, 1, 7, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (451, 3, 18, 43, 94, 1, 8, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (452, 3, 18, 43, 94, 1, 9, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (453, 3, 18, 53, 92, 1, 10, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (454, 3, 18, 53, 92, 1, 11, 'Quinta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (455, 3, 18, NULL, NULL, 1, 6, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (456, 3, 18, NULL, NULL, 1, 7, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (457, 3, 18, NULL, NULL, 1, 8, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (458, 3, 18, NULL, NULL, 1, 9, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (459, 3, 18, NULL, NULL, 1, 10, 'Sexta');
INSERT INTO aulas (id , curso_id, turma_id, professor_id, materia_id, sala_id, horario_id, dia_semana) VALUES (460, 3, 18, NULL, NULL, 1, 11, 'Sexta');